version: '3'
services:
  www:
    image: tokumeikoi/lcrp
    volumes:
      - './www:/www'
      - './wwwlogs:/wwwlogs'
      - './caddy.conf:/run/caddy/caddy.conf'
      - './supervisord.conf:/run/supervisor/supervisord.conf'
      - './susu.conf:/etc/supervisor/conf.d/supervisord.conf'
      - './crontabs.conf:/etc/crontabs/root'
      - './.caddy:/root/.caddy'
    ports:
      - '8081:80'
    restart: always
    networks:
      - v2b
  mysql:
    image: mysql:5.7.29
    volumes:
      - './mysql:/var/lib/mysql'
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: v2boardisbest
      MYSQL_DATABASE: v2board
    networks:
      - v2b
networks:
  v2b:
    driver: bridge
